name: "ğŸ’£ Snyk"

on:
  push:
    tags: ["v[1-9]+.[0-9]+.[0-9]"]
  pull_request:
    branches: ["main"]
    types: ["opened", "synchronize", "reopened"]

jobs:
  security-scan:
    name: ğŸ” Security scan
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v2

      - name: ğŸ”§ Use .NET 6.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: ğŸ”¨ Build
        run: dotnet build ./Tethos.sln --configuration Release

      - name: ğŸ”“ Run Snyk scan
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=critical
