name: ğŸ” Spellcheck

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: ğŸ”¦ Spelling
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v2

      # - name: âœ… Check
      #   uses: check-spelling/check-spelling@v0.0.20-alpha3

      - name: Spellcheck
      uses: rojopolis/spellcheck-github-actions@0.18.0